[package]
name = "million_bits_ca"
version = "0.1.0"
authors = ["barba"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
compression = "0.1"
bv = "0.11.1"